- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: install or uninstall packages
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}" # item is a default keyword
      loop:
        - {name: 'git', state: 'present'} # item(this whole line is item) fro here it goes to item.name  - denotes list and in list having multiple values.
        - {name: 'mysql', state: 'absent'}
        - {name: 'postfix', state: 'absent'}
        - {name: 'nginx', state: 'present'}